export const CATEGORIES_ACTION_TYPE = {
  // With Redux Thunk (Async)
  FETCH_CATEGORIES_START: "category/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "category/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "category/FETCH_CATEGORIES_FAILED",
  // Without Redux Thunk
  /*SET_CATEGORIES: "category/SET_CATEGORIES",*/
};